### ISSUE TITLE
Support for Unity

### ISSUE THREAD

**Issue by mjkoehle** [BrannonKing/NLoptNet#10]
Please forgive me if this isn't the place to ask this question. I am trying to use this within Unity and my script fails to locate libnlopt-0.dll. Will this work as is within Unity?

**Comment by BrannonKing** [comment]
I have never used unity. Is it just a deployment issue? Can you manually copy the DLL, or add some pre-build step to do it, or add a copy-reference to your main program project?

**Comment by mjkoehle** [comment]
I'm fairly new to Unity. It doesn't like duplicate names for DLL's added to its assets, so in NloptSolver.cs, I took out the logic around which version of linlopt-0.dll to add, and give LoadLibrary the full path. I can now locate the library, but I'm getting a different error. I am trying to run one of the unit test examples, TestBasicParabolaNoDerivative. I can declare a new NLoptSolver, set it's lower and upper bounds, but running solver.Optimize gives an exception: NullReferenceException: Object reference not set to an instance of an object. It looks to me that all the inputs into solver.Optimize are as they should be. I suspect it's still a deployment issue. As far as I can tell, the call to the c++ library looks ok. I can't really debug past that point from within unity. I'll let you know if I get it working.

**Comment by BrannonKing** [comment]
Make sure that you're using the correct DLL for your process (32bit vs 64bit). If you could get a call stack on the exception, that would be helpful. Feel free to post the example code that reproduces the problem.

**Comment by mjkoehle** [comment]
Here's a code snippet - it's essentially a copy of the Parabola No Derivative unit test. 

    static void TestBasicParabolaNoDerivative()
    {
        for (int i = 0; i <= (int)NLoptAlgorithm.GN_ESCH; i++)
        {
            var algorithm = (NLoptAlgorithm)i;
            var algStr = algorithm.ToString();
            if (algStr.Contains("AUGLAG") || algStr.Contains("MLSL"))
                continue;
            if (algStr.Substring(0, 3).Contains("D_"))
                continue;
            var sw = Stopwatch.StartNew();
            int count = 0;
            using (var solver = new NLoptSolver(NLoptNet.NLoptAlgorithm.GN_DIRECT_L, 1, 0.0000001, 2000))
            {
                solver.SetLowerBounds(new[] { -10.0});
                solver.SetUpperBounds(new[] { 100.0 });
                solver.SetMinObjective(variables =>
                {
                    count++;
               =>double total = Math.Pow(variables[0] - 3.0, 2.0) + 4.0;
                    return total;
                });
                double? final;
                var data = new[] { 2.0 };
                var result = solver.Optimize(data, out final);
                Trace.WriteLine(string.Format("D:{0:F3}, R:{1:F3}, A:{2}, {3}", data[0], final.GetValueOrDefault(-1), algorithm, result));
            }
            Trace.WriteLine("Elapsed: " + sw.ElapsedMilliseconds + "ms, Iterations: " + count);
        }
    }

Once solver.Optimize is called, it runs through one calculation of the objective function, using a value of 45. It then fails on its second pass through SetMinObjective on the line:
nlopt_func func = (u, values, gradient, data) => objective.Invoke(values);

If I run this in C#, I can see Values for u, values, gradient, and data right before this line. I'm not able to in Unity. But I don't know if this is a peculiarity of debugging in Unity or if these really aren't defined. 

If I have the 32 libnlopt-0.dll, Unity does not locate the library at all, and i don't get this far.  

This is the call stack:
Double <>c__DisplayClass45_0:<SetMinObjective>b__0 (UInt32, Double[], Double[], IntPtr)+0xc at C:\Users\t_koehm\source\repos\NLoptNet-master Working\NLoptNet-master\NLoptNet\NLoptSolver.cs:[290:53-290:77]	C#
 	NloptResult NLoptNet.NLoptSolver:Optimize (Double[], Nullable`1)+0x14 at C:\Users\t_koehm\source\repos\NLoptNet-master Working\NLoptNet-master\NLoptNet\NLoptSolver.cs:[341:4-341:63]	C#
 	Void ikSolver_2:TestBasicParabolaNoDerivative ()+0xef at C:\Users\t_koehm\Documents\work\ROBOTs\UNITY GENERAL\IKTEST\Assets\ikSolver_2.cs:777	C#
 	Void ikSolver_2:Start ()+0x184 at C:\Users\t_koehm\Documents\work\ROBOTs\UNITY GENERAL\IKTEST\Assets\ikSolver_2.cs:116	C#

**Comment by BrannonKing** [comment]
Ever make this work?

**Comment by JeremyBois** [comment]
Hi, I have the same issue with Unity 2019.4.16f1 using 64bits C++ DLL.

```C#
using (var solver = new NLoptSolver(NLoptAlgorithm.LN_COBYLA, 1))
{
        solver.SetLowerBounds(new[] { -10.0 });
        solver.SetUpperBounds(new[] { 100.0 });

        solver.SetMinObjective(variables =>
        {
            return Math.Pow(variables[0] - 3.0, 2.0) + 4.0;
        });

        double? finalScore;
        var initialValue = new[] { 2.0 };
        var result = solver.Optimize(initialValue, out finalScore);
}
```

I directly used the source code to investigate a little more and the problem occurs with `nlopt_optimize` native function call.
```
NullReferenceException: Object reference not set to an instance of an object
NLoptNet.NLoptSolver.Optimize (System.Double[] initialValues, System.Nullable`1[System.Double]& finishingObjectiveScore) (at Assets/_Main/LogicalSimulator/NLopt/NLoptSolver.cs:330)
NLopt_tests.Start () (at Assets/_Main/VisualSimulator/1_Scenes/TestScenes/NLopt/NLopt_tests.cs:36)
```

This error occurs for `NLoptAlgorithm.LN_COBYLA` where there is no issues with `NLoptAlgorithm.LD_MMA` or `NLoptAlgorithm.LD_AUGLAG` or `NLoptAlgorithm.LD_SLSQP`.

**Comment by BrannonKing** [comment]
Can you tell me if you're using the v1.2 or v1.3 package? If on v1.2, can you try the v1.3?

**Comment by JeremyBois** [comment]
I tried both version from nuget, same result.
Now I am using the source files (from this repository) for the C# part and the C++ DLLs provided.

I think the issue comes from the C++ part.
Maybe the LN_COBYLA solver make use of a specific behavior that make the marshalling to fail when trying to get the `finalScore` value ?

Which NLopt version are you using ? Maybe I can tried one of the pre-built binaries [here](https://conan.io/center/nlopt?os=Windows&tab=configuration).

**Comment by BrannonKing** [comment]
Make sure that your Unity project is also set to target 64bit. I was using version 2.6.1. All of those versions should likely work: it appears that the interface is quite stable.

**Comment by JeremyBois** [comment]
My project build target is 64bit. I currently only run it in the editor which is also 64bit.

Unity uses `mono` as scripting backend and use `.Net 4.0` as API level. I doubt it can come from this because the library is correctly linked.

**Comment by JeremyBois** [comment]
I investigate a little more with this issue. It seems related to gradient free algorithm (ones that does not required gradient to be computed).

When `Optimize` is called, the first step is done correctly (objective function called). However just after the objective function call `Dispose` is reached releasing the optimizer pointer leading to the `NullReferenceException`.

Yet, I do not understand why `Dispose` is called ...


Below the whole code used in Unity. In order to test it, just create a scene and add this script to any gameobject.
```csharp
using System;
using System.Collections.Generic;
using UnityEngine;
using NLoptNet;


public class NLopt_tests : MonoBehaviour
{
    void Start()
    {
        // Ok !
        TestGradientBased(NLoptAlgorithm.LD_SLSQP);
        
        // NullReference error !
        TestGradientFree(NLoptAlgorithm.LN_COBYLA);
    }

    public void TestGradientBased(NLoptAlgorithm algorithm)
    {
        var gradientsHistory = new List<double[]>();
        var variablesHistory = new List<double[]>();
        double? finalScore;
        NloptResult result;
        int count = 0;

        using (var solver = new NLoptSolver(algorithm, 2, maximumIterations: 20))
        {
            var initialValue = new[] { 1.234, 5.678 };
            solver.SetLowerBounds(new[] { 1.0, 1.0 });
            solver.SetUpperBounds(new[] { 10.0, 10.0 });

            solver.SetMinObjective((variables, gradient) =>
            {
                var h = 0.00001;
                var f0 = Math.Pow(variables[1] * variables[0], 2);
                var fi0 = Math.Pow(variables[1] * (variables[0] + h), 2);
                var fi1 = Math.Pow((variables[1] + h) * variables[0], 2);

                if (gradient != null)
                {
                    // two point numerical differentiation
                    gradient[0] = (fi0 - f0) / h;
                    gradient[1] = (fi1 - f0) / h;
                }
                count++;

                var iterationGradients = new double[2];
                Array.Copy(gradient, iterationGradients, 2);
                gradientsHistory.Add(iterationGradients);

                var iterationValues = new double[2];
                Array.Copy(variables, iterationValues, 2);
                variablesHistory.Add(iterationValues);

                return f0;
            });

            result = solver.Optimize(initialValue, out finalScore);
            Debug.Log($"({algorithm}) --> Target value = {finalScore.Value} (nloptCode={result})");
        }

        for (int i = 0; i < count; i++)
        {
            Debug.Log($"#{i} --> variables=({variablesHistory[i][0]}, {variablesHistory[i][1]}) - gradient=({gradientsHistory[i][0]}, {gradientsHistory[i][1]})");
        }
    }

    public void TestGradientFree(NLoptAlgorithm algorithm)
    {
        var gradientsHistory = new List<double[]>();
        var variablesHistory = new List<double[]>();
        double? finalScore;
        NloptResult result;
        int count = 0;

        using (var solver = new NLoptSolver(algorithm, 2, maximumIterations: 20))
        {
            var initialValue = new[] { 1.234, 5.678 };
            solver.SetLowerBounds(new[] { 1.0, 1.0 });
            solver.SetUpperBounds(new[] { 10.0, 10.0 });

            solver.SetMinObjective((variables) =>
            {
                var f0 = Math.Pow(variables[1] * variables[0], 2);
                count++;

                var iterationValues = new double[2];
                Array.Copy(variables, iterationValues, 2);
                variablesHistory.Add(iterationValues);

                return f0;
            });

            result = solver.Optimize(initialValue, out finalScore);
            Debug.Log($"({algorithm}) --> Target value = {finalScore.Value} (nloptCode={result})");
        }

        for (int i = 0; i < count; i++)
        {
            Debug.Log($"#{i} --> variables=({variablesHistory[i][0]}, {variablesHistory[i][1]})");
        }
    }

    private double TestEq(double[] values, double[] grads)
    {
        return 0.0;
    }
}
```

**Comment by BrannonKing** [comment]
Are you catching all exceptions? Is that even possible with Mono. I've never used Mono. All I can figure is that this must be some bug in Mono. Is there some way to make Unity use .NET 5 or 6 instead?

**Comment by JeremyBois** [comment]
No Unity can only use mono or IL2CPP (never used it). Compatibility is enforced only with .Net 4 for settings shared between multiple platforms. 

I see in NLoptNet project settings that the target is set correctly to a standard (`netstandard2.0`). So the library enforced the use of only a common set of features shared between both .Net and mono.

Can you try to run this script in Unity on your side ?

**Comment by JeremyBois** [comment]
There is a difference in how marshalling must be done in mono and in .Net. 

Similar issue and solution implementation at cureos/csipopt#2

**Comment by BrannonKing** [comment]
Nice find! It looks like you correctly identified the bug. I think what we could do is make an a separate nlopt_func definition that anticipates that being null. In other words, add this definition: 
```csharp
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
private delegate double nlopt_func_nograd(uint n, [MarshalAs(UnmanagedType.LPArray, SizeParamIndex = 0), In] double[] x, IntPtr gradient, IntPtr data);
```
Then modify `SetMinObjective` (the one that doesn't expose the gradient) to this:
```csharp
public void SetMinObjective(Func<double[], double> objective)
{
	nlopt_func_nograd func = (u, values, gradient, data) => objective.Invoke(values);
	...
```
We would also change the func type in `AddLessOrEqualZeroConstraint` and verify that `gradient == IntPtr.Zero` there. The `_funcCache` exists just to keep the functions from the GC. Its value type could change to `object`, and that would still achieve the necessary purpose there.

**Comment by JeremyBois** [comment]
Actually I have already made the changes to my own files and I test with different algorithm and all seems to work correctly.

I remove all occurrence of `MarshalAs` (as in cureos/csipopt#2) because I am not sure this is supported in mono at all.

I have made other changes to the codebase but cannot find the time yet to make pull requests:

- Add multiple constraints support (eq and ieq)
- Add up to date algorithms that support equality constraint based on Cpp codebase (AUGLAG variants)
- Add fix of this issue for mono (and Unity)

I will make pull requests when I can. In the meantime source code can be found [here](https://pastebin.com/F8VdfpEP) and tests [here](https://pastebin.com/1j8wkabV).

**Comment by JeremyBois** [comment]
I open 3 pull request one of which solves this issue. Feel free to merge them ...

**Comment by BrannonKing** [comment]
@JeremyBois and @mjkoehle , the newer versions of Mono (5+) no longer support the __MonoCS__ predefine. It doesn't run for me on Mono on Linux, but it looks like @JeremyBois 's alternative Unity predefine probably still works. Do we need to repair Mono support? Go with a runtime detection approach instead? Or is the .net core support sufficient for Linux use these days?

**Comment by Ted-Barrett** [comment]
For anyone who sees this in the future, I was having trouble installing it in unity, here's how I did it:

## Step 1: Install NLoptNet

### Option 1: Use NuGetForUnity

1. Install [NuGetForUnity](https://github.com/GlitchEnzo/NuGetForUnity) (click "install via package manager" in the readme and follow the instructions)
3. Install NLoptNet using NuGetForUnity

### Option 2: Download manually

1. Download NLoptNet from nuget [here](https://www.nuget.org/packages/NLoptNet)
2. Extract the nupkg (you can use 7-zip for this)
4. Go to `[folder you just extracted]/lib/net47` and copy `NLoptNet.dll` to your `Assets/Plugins` folder (create one if it doesn't exist) in your unity project.

## Step 2: Add nlopt dependency

1. Go to [the runtimes folder](https://github.com/BrannonKing/NLoptNet/tree/master/NLoptNet/runtimes/win-x64/native) and download the dll
2. Copy this to the `Assets/Plugins` folder in your project and rename to `nlopt_x64`
4. Done!
