### ISSUE TITLE
Cannot add equality constraint

### ISSUE THREAD

**Issue by Metal10k** [BrannonKing/NLoptNet#2]
I have just been playing around with this wrapper and it looks like currently there is no way to add an equality constraint (I believe some algorithms treat these differently?). The underlying API is: 
void nlopt::opt::add_equality_constraint(nlopt::vfunc h, void *h_data, double tol=0);
http://ab-initio.mit.edu/wiki/index.php/NLopt_C-plus-plus_Reference

I have had a brief look at the code, and importing the call looks like it shouldn't be too awkward
```c#
		[DllImport("libnlopt-0.dll", CallingConvention = CallingConvention.Cdecl)]
		private static extern NloptResult nlopt_add_equality_constraint(IntPtr opt, nlopt_func h, IntPtr data, double tolerance);
```

Creating a new wrapper on the NLOptSolver I am not entirely sure about though. I assume we will need something like:

```c#
		public void AddEqualityConstraint(Func<double[], double[], bool> constraint, double tolerance = 0.001)
		{
			nlopt_SomeNewfunc func = (u, values, gradient, data) => constraint.Invoke(values, gradient);
			_funcCache.Add(constraint, func);
			var res = nlopt_add_equality_constraint(_opt, func, IntPtr.Zero, tolerance);
			if (res != NloptResult.SUCCESS)
				throw new ArgumentException("Unable to add the constraint. Result: " + res, "constraint");
		}
```
Curious if this is feasible.

**Comment by Martin1994** [comment]
I recommend you read the source code of NLopt. You will see that only a few algorithm support equality constraint. However, in NLopt wiki they didn't tell you about this. There is a function (equality_ok() in api/options.c) in NLopt to check whether an algorithm can use equality constraint (and another to check inequality constraint as well).

In short, you can only apply equality constraint if your algorithm is NLOPT_LD_SLSQP, NLOPT_GN_ISRES or NLOPT_LN_COBYLA.

**Comment by BrannonKing** [comment]
Thanks for the request. I will include your `AddEqualityConstraint` method in a build coming by the end of the week. It seems I should throw an exception if the chosen algorithm is not one of the three that @Martin1994 listed?

**Comment by BrannonKing** [comment]
New package with the pull request is done, pushed, and uploaded to the Nuget Gallery. Give it a go! Closing this issue...

**Comment by Metal10k** [comment]
Much appreciated. Thanks!
