### ISSUE TITLE
Using NLoptNet in .NET Framework

### ISSUE THREAD

**Issue by rlordcardano** [BrannonKing/NLoptNet#20]
I recently had a look at using NLOptNet - works very well out of the box in e.g. a .NET Core 3.1 test project.
However, when changing the target framework to .NET 4.7 I get:

`System.DllNotFoundException : Unable to load DLL 'nlopt': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
`

I've managed to solve this locally by adding a LoadLibrary step in a static constructor of the NLoptSolver class.
Happy to suggest these changes in a PR if there is interest - obviously realising that .NET Framework is not the future, and therefore may be less relevant to the community.

**Comment by BrannonKing** [comment]
You can see here that there used to be a LoadLibrary call in the codebase: https://github.com/BrannonKing/NLoptNet/commit/72be44053fd4ed933d4a860238c2eccc1c0742e5

It's probably just missing the right RID folder in the runtimes folder (near the EXE). I'm just not sure what the right folder name would be for that.

**Comment by rlordcardano** [comment]
Right - I see you've got a LoadLibrary in the [tests](https://github.com/BrannonKing/NLoptNet/blob/master/NLoptNet.Tests/SolverTests.cs) as well.

A similar load, where it checks the architecture it's running on, and then attempts to load the library, like [here](https://github.com/mathnet/mathnet-numerics/blob/796923641c568e8ff443a9876053484aa739e915/src/Providers.MKL/NativeProviderLoader.cs), does the trick.

Happy to suggest a PR.

**Comment by BrannonKing** [comment]
It seems that a solution that doesn't use LoadLibrary is possible. See here: https://stackoverflow.com/a/52471739/1208289

**Comment by rlordcardano** [comment]
Thanks for that, that was helpful! Hotchpotch is the word that comes to mind.

I've put something together that targets .NET 4.7 and .NET Standard, and works in both 32-bit and 64-bit (at least on a Windows machine). Downside is that you can't avoid LoadLibrary for .NET Framework as it seems. Will make a fork on my private account and share in that way here.

**Comment by rogerlord** [comment]
Please have a look at [this](https://github.com/rogerlord/NLoptNet/pull/4) - earlier closed PRs in the fork mainly centered around setting up GitHub Actions to build & test the solution.

As mentioned above, it does seem to work now for .NET Standard and .NET 4.7. Happy to see if the continuous integration pipeline can be used to test other use cases as well, I've currently only set it up for Windows tests. But should be easy to get the pipeline to test things simultaneously on Linux as well.

Let me know if there is interest in incorporating this in the main codebase.

**Comment by BrannonKing** [comment]
@rogerlord , I just looked through your changes in the link. I would be fine merging them here, assuming that warning only shows in the .NET 4.7 use case.

**Comment by rogerlord** [comment]
Hi @BrannonKing - I've raised a PR - #23 for this.
Indeed, when you compile NLoptNet.NuGet.Tests.csproj for .NET Core 3.1 or .NET 5.0 / 6.0, it will not give the warning that is present in .NET Framework 4.7 or 4.8.
