### ISSUE TITLE
Build warnings in version 1.4.0.0

### ISSUE THREAD

**Issue by jacobwvandijk-work** [BrannonKing/NLoptNet#25]
If updated from 1.3.0.0 to 1.4.0.0 and see these warnings (compiling to Any CPU):

Microsoft.Common.CurrentVersion.targets(2202, 5): [MSB3246] Resolved file has a bad image, no metadata, or is otherwise inaccessible. System.BadImageFormatException: Could not load file or assembly 'nlopt_x32.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'nlopt_x32.dll' ---> System.BadImageFormatException: Could not load file or assembly 'nlopt_x32.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'nlopt_x32.dll'
...

Also for nlopt_x64. It noticed that the lib folder of the package has changed that seems to cause this. Is this an unseen side effect of a change?

Here is the quite verbose warning:

Warning MSB3246 : Resolved file has a bad image, no metadata, or is otherwise inaccessible. System.BadImageFormatException: Could not load file or assembly 'nlopt_x64.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'nlopt_x64.dll' ---> System.BadImageFormatException: Could not load file or assembly 'nlopt_x64.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'nlopt_x64.dll'
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at Microsoft.Build.Shared.AssemblyNameExtension.GetAssemblyNameEx(String path)
   at Microsoft.Build.Tasks.SystemState.GetAssemblyName(String path)
   at Microsoft.Build.Tasks.ReferenceTable.SetPrimaryAssemblyReferenceItem(ITaskItem referenceAssemblyName)

**Comment by rogerlord** [comment]
Hi @jacobwvandijk-work - apologies for the late reply.

Yes - known side-effect, I've posted a question [here](https://stackoverflow.com/questions/52397501/nuget-references-to-assemblies-in-runtimes-folder-not-added/70453755#70453755) for advice, but no luck yet. The warning is caused by the fact that this is not the intended way to include native libraries (it expects a .NET library) when targeting .NET Framework.

Hoping an easy way materialises to work around it, alternatively - we can look into providing a separate project file that targets .NET Framework only.

**Comment by rogerlord** [comment]
Hi @jacobwvandijk-work - just to let you know I haven't forgotten about this.

I have a PR [here](https://github.com/rogerlord/NLoptNet/pull/10) that should do the job, it uses a .nuspec file to generate a package that contains both the .NET Framework requirements as well as the .NET Standard ones. Still generates some warnings when the package is generated, but no more warnings when users consume the package - which is what I think is preferred.

Will clean up in the course of this week and submit it as a PR to this repository.

**Comment by rogerlord** [comment]
Have finished it - PR now here: https://github.com/BrannonKing/NLoptNet/pull/27.

**Comment by rogerlord** [comment]
Update - no more warnings are generated during the package generation either - @BrannonKing - this is ready for review now.

**Comment by jacobwvandijk-work** [comment]
Great Brannon, thanks for picking this up.

Op do 31 mrt. 2022 om 16:38 schreef Brannon King ***@***.***>:

**Comment by BrannonKing** [comment]
Yeah, @jacobwvandijk-work, the 1.4.1 update was published on nuget.org. Let me know if you see any issues with it.
