### ISSUE TITLE
AddLessOrEqualZeroConstraints does not work

### ISSUE THREAD

**Issue by svenjoh** [BrannonKing/NLoptNet#33]
`AddLessOrEqualZeroConstraints(Action<double[], double[], double[]> constraints, double[] tolerances)` does not work as expected. When `constraints` is called, the supplied `double[] gradient` will have an incorrect length.

An mfunc is used here:
https://github.com/BrannonKing/NLoptNet/blob/a8561e53e70bbe9b4a79e638cbd19af281f9f29e/NLoptNet/NLoptSolver.cs#L285

mfunc is defined as:
https://github.com/BrannonKing/NLoptNet/blob/a8561e53e70bbe9b4a79e638cbd19af281f9f29e/NLoptNet/NLoptSolver.cs#L47

but the length of `gradient` cannot be taken as `SizeParamIndex = 2` when used in `AddLessOrEqualZeroConstraints`. It is supposed to be `m*n`. Any example with two or more constraints will break.

**Comment by BrannonKing** [comment]
Good catch! From their docs:

> void c(unsigned m, double \*result, unsigned n, const double\* x, double\* grad, void\* f_data);
> This evaluates the constraint function(s) c(x) at the point x, an array of length n (the same as the dimension passed to nlopt_create). Upon return, the output value of the constraints should be stored in result, an array of length m (the same as the dimension passed to nlopt_add_\*_mconstraint), so that result[i] stores ci. In addition, if grad is non-NULL, then grad points to an array of length m*n which should, upon return, be set to the gradients of the constraint functions with respect to x. The n dimension of grad is stored contiguously, so that ∂ci/∂xj is stored in grad[i\*n + j]. An inequality constraint corresponds to ci≤0 for 0≤i<m, and an equality constraint corresponds to ci=0, in both cases with tolerance tol[i] for purposes of termination criteria.

I'll be pondering on the right way to fix this, and I'm open to suggestions. I guess I'll have to return the pointer and do my own marshalling.

**Comment by svenjoh** [comment]
Don't know if there is a way to avoid the explicit marshalling. The MONO code here https://github.com/BrannonKing/NLoptNet/blob/a8561e53e70bbe9b4a79e638cbd19af281f9f29e/NLoptNet/NLoptSolver.cs#L35
and here
https://github.com/BrannonKing/NLoptNet/blob/a8561e53e70bbe9b4a79e638cbd19af281f9f29e/NLoptNet/NLoptSolver.cs#L524
seems ok but with `gradient` as `m*n` and `Marshal.Copy` calls fixed accordingly.

**Comment by svenjoh** [comment]
Don't know if there is a way to avoid the explicit marshalling. The MONO code here https://github.com/BrannonKing/NLoptNet/blob/a8561e53e70bbe9b4a79e638cbd19af281f9f29e/NLoptNet/NLoptSolver.cs#L35
and here
https://github.com/BrannonKing/NLoptNet/blob/a8561e53e70bbe9b4a79e638cbd19af281f9f29e/NLoptNet/NLoptSolver.cs#L524
seems ok but with `gradient` as `m*n` and `Marshal.Copy` calls fixed accordingly.

**Comment by svenjoh** [comment]
Don't know if there is a way to avoid the explicit marshalling. The MONO code here https://github.com/BrannonKing/NLoptNet/blob/a8561e53e70bbe9b4a79e638cbd19af281f9f29e/NLoptNet/NLoptSolver.cs#L35
and here
https://github.com/BrannonKing/NLoptNet/blob/a8561e53e70bbe9b4a79e638cbd19af281f9f29e/NLoptNet/NLoptSolver.cs#L524
seems ok but with `gradient` as `m*n` and `Marshal.Copy` calls fixed accordingly.

**Comment by BrannonKing** [comment]
@svenjoh , please look at my latest commit; make sure it looks right.

**Comment by svenjoh** [comment]
Looks good to me. Thanks for fixing!
