### ISSUE TITLE
Malware in libnlopt-0.dll x64

### ISSUE THREAD

**Issue by jorritjaap** [BrannonKing/NLoptNet#5]
Hi BrannonKing,

My virsus scanner indicated malware embedded in x64 libnlopt-0.dll bundled with version 1.0.2.0.

Hope this helps.

Best regards,

Jorrit

**Comment by BrannonKing** [comment]
Can you run your virus scanner on the original DLLs found here?
http://ab-initio.mit.edu/wiki/index.php/NLopt_on_Windows

Also, what virus scanner and version are you using?

**Comment by jorritjaap** [comment]
No problem. The original DLLs in the link (nlopt-2.4.2) are clean, but I believe you are linking older version?

I am using latest version of g-data (https://www.gdata.nl/). 

Let me know if I can help with more details.

**Comment by BrannonKing** [comment]
As far as I can tell, the DLLs packaged in my Nuget package are identical to the ones available in the source link from MIT. I just diff'd the files extracted from the package that I uploaded to Nuget with the MIT source files, and WinMerge responds that they are identical.

**Comment by jorritjaap** [comment]
I am not sure what happens, but if I pull the code and do a scan I get 

![image](https://cloud.githubusercontent.com/assets/11610925/6797244/d4e6f460-d1ff-11e4-9881-8d695595c88a.png)


![capture](https://cloud.githubusercontent.com/assets/11610925/6797233/b43e51a4-d1ff-11e4-8147-d598896b8830.PNG)

**Comment by BrannonKing** [comment]
What Nuget repository do you have configured in Visual Studio? Where exactly did you get those packages? Are you pulling from some questionable mirror?

**Comment by jorritjaap** [comment]
Only the default ones are set:
-https://www.nuget.org/api/v2/
-https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/

Note that I already get the virus hit on the latest version on Github, so I
don't think it has to do with NuGet.

2015-03-24 17:17 GMT+01:00 Brannon King <notifications@github.com>:

> What Nuget repository do you have configured in Visual Studio? Where
> exactly did you get those packages? Are you pulling from some questionable
> mirror?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrannonKing/NLoptNet/issues/5#issuecomment-85586776>.
>



-- 


Jorrit-Jaap de Jong
uGly Duckling B.V.
Burgemeester le Fevre de Montignylaan 30
3055LG Rotterdam, the Netherlands

KvK nummer: 52272125
BTW nummer: NL850371570B.01
Rabobank: NL40 RABO 0146 8334 73
E: j.jong@uglyduckling.nl
T : +31 (0)10 2602444
M: +31 (0)6 24552454
W: http://uGlyDuckling.nl <http://www.uglyduckling.nl/>

LinkedIn : http://www.linkedin.com/in/jorritjaap

**Comment by BrannonKing** [comment]
I'm confident that there are no viruses in the DLLs that I packaged. If the DLLs differ from what is available on the MIT site, then they must have been modified on the end-user machine. Closing...
