### ISSUE TITLE
AUGLAG with child algorithm

### ISSUE THREAD

**Issue by sonntagdaniel** [BrannonKing/NLoptNet#9]
Just a quick comment/issue, as it took me quite a while to figure this out in my code, maybe it will come in handy for anybody who reads this: right now the tolerance on the child algorithm can only be set when creating the NLOptSolver and will be set automatically as a relative tolerance on the variables change (which may or may not make sense). 

When relativeStoppingTolerance is set to 0.0 (maybe because later on a relativeStoppingTolerance on the objective function is set), the algorithm will fail (or at least failed in my test cases).

**Comment by BrannonKing** [comment]
As is typical with these iterative algorithms, a tolerance of absolute 0.0 is unachievable. It sounds like it would be valuable to add bounds checks on the tolerance values. And I'm open to other methods to set various tolerances in NLopt. I'm open to PRs for either of those.
